name: metadata
description: metadata helps to extract metadata from your files.
version: 1.0.1
homepage: https://github.com/justkawal/metadata.git

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  xmp: 1.0.0

dev_dependencies:
  #pedantic: ^1.9.0
  #test: ^1.14.4
